### ISSUE TITLE
Script not working

### ISSUE THREAD

**Issue by R4Ajeti** [deniscerri/filma24-cli#2]
I followed all the steps #Refs for installation on Windows using git bash
It isn't working I am getting this error: "Couldn't reach site!"

using:
base_url=$(curl -A $user_agent -s --connect-timeout 5 --head -L https://www.filma24.gd | grep -oP "location: \K.*")
base_url always gives nothing as output

but using:
base_url=$(curl -A $user_agent -s --connect-timeout 5 --head -L https://www.filma24.gd)
Cloudflare output report will never give you "location" as many times as I try to run it

Refs: https://github.com/deniscerri/filma24-cli/blob/main/README.md

**Comment by deniscerri** [comment]
looks like your network cant access filma24 directly. You need to find a way to access it directly with simple curl commands otherwise you cant use the tool.
