### ISSUE TITLE
Sugjerim perdorimi i yt-dlp ne vend te ffmpeg 

### ISSUE THREAD

**Issue by diekaines** [deniscerri/filma24-cli#3]
Pershendetje

Ne rradhe te pare urime per kete bash script. 

E perdora 2-3 here dhe punon ok.  

Provova nje link me kete script edhe do diku tek 20-30 minuta te shkarkohet.  
https://www.filma24.pl/gran-turismo-2023-me-titra-shqip/  (  iframe  https://vidmoly.net/embed-zf38qn5cat5c.html  ) 

Provova te njejtin link me yt-dlp  ( https://github.com/yt-dlp/yt-dlp  )  edhe shkarkimi eshte shume here me i shpejte  ( 1:50 minuta ) 

```
C:/temp> yt-dlp.exe https://vidmoly.net/embed-zf38qn5cat5c.html                                                                                                                                          
[generic] Extracting URL: https://vidmoly.net/embed-zf38qn5cat5c.html
[generic] embed-zf38qn5cat5c: Downloading webpage
.....
[download] Destination: video [master].mp4
[download] 100% of    1.36GiB in 00:01:51 at 12.52MiB/s
[FixupM3u8] Fixing MPEG-TS in MP4 container of "video [master].mp4"
```

Mbase eshte me mire te perdoret yt-dlp

Gjithe te mirat

**Comment by deniscerri** [comment]
E kam menduar ta shtoj, gjithashtu ta perdor per te gjetur streams kur deshton skripti

**Comment by deniscerri** [comment]
@diekaines u be

**Comment by diekaines** [comment]
Te lumshin duart :)

**Comment by R4Ajeti** [comment]
Faleminderit shume @diekaines per kete informacion
E testova edhe une te nejtin link qe e ke dergu ne browser edhe tu e perdor yt-dlp nuk e di se si (noshta e downloadon prej me shum se 1 source si streaming paralelisht e tani i bashkon ne fund) ama shpejtesia eshte e pakrahasueshme. Nashta ka naj limit tjeter rruges, koka mire me test me lloje te embeded links, direct links, streaming links.

**Comment by diekaines** [comment]
@R4Ajeti 

https://www.reddit.com/r/youtubedl/comments/q6nq3d/ytdlp_m3u8hls_native_vs_ffmpeg_downloader/

```
noshta e downloadon prej me shum se 1 source si streaming paralelisht e tani i bashkon ne fund
```

Fiks ate ben yt-dlp :) 

tung
